Dun-sin/Code-Magic

- src/main.ts
> docs: comments for functions

- src/main.ts
- src/style.css
- Giving pic-text it's own function
- a function to check which generator was clicked and call the function accordingly
> feat: each generator having their own function

- index.html
- src/main.ts
- src/style.css
- Did some refactoring
- Basic Structuring for text gradient generator
> Text gradient generator

- README.md
> docs: beer emoji

- index.html
- src/main.ts
- src/style.css
- add functionality for the text gradient generator
> feat: functionality of text gradient generator

- index.html
- src/style.css
- add a link to the GitHub repo
> feat: link to github repo

- index.html
> feat: exo2 font

- index.html
- src/main.ts
- src/style.css
- add warning note for download in pic-text generator
> feat: warning note

- .github/workflows/release.yml
> chore: release workfolow

- .github/workflows/build.yml
> chore: build action

- .github/workflows/greetings.yml
<!-- If your PR fixes an open issue, use `Closes #101` to link your PR with the issue. #101 stands ## 👨‍💻 Changes proposed
- greeting action for first timer
> chore: greetings action

- .github/workflows/merge-pr.yml
- create merge pull request action
> chore: mergePR action

- package.json
- src/main.ts
- src/style.css
- src/utils/general.ts
- src/utils/gradient-text.ts
- src/utils/pic-text.ts
- Every generator has its own module/file
> refactor: each generator has it's own module

- .github/workflows/deployment.yml
- .github/workflows/greetings.yml
- src/utils/pic-text.ts
- github action for comment shouldn't work on merged PR
- fix error on build
> build: fix error on build

- README.md
- Add Instructions in `readme.md` for pushing to GitHub
> docs(readme.md): add instructions for pushing to github

- README.md
- src/main.ts
- Add event listener for when the escape key is pressed to close modal
> Feat: use escape to close modal

- README.md
- index.html
- src/main.ts
> feat: change footer text

- .github/workflows/greetings.yml
- Add link to join the community
> chore: add community

- README.md
- index.html
- src/general.ts
- src/generators/gradient-text.ts
- src/main.ts
- add functionality to download the result in image and svg form
> feat: add functionality to download as image in text generator

- README.md
- index.html
- src/general.ts
- src/generators/gradient-text.ts
- src/generators/pic-text.ts
- src/main.ts
> fix: wrong passing of arguments in download function

- README.md
- index.html
- src/general.ts
- src/generators/gradient-border.ts
- src/generators/gradient-text.ts
- src/generators/pic-text.ts
- src/main.ts
- src/style.css
- Add the new gradient border generator
- refactored by applying the dry principle
> feat: add gradient border generator

- src/general.ts
- Convert regular functions that could be converted to one line code using arrow functions
> refactor: use arrow function for short functions

- src/general.ts
Convert this functions because they can be placed with one line of code
<!-- If your PR fixes an open issue, use `Closes #101` to link your PR with the issue. #101 stands ## 👨‍💻 Changes proposed
- convert some regular functions to arrow functions
> refactor(general.ts): convert some regular functions to arrow functions

- src/style.css
> feat(style.css): animate the header text

- src/main.ts
- add when user clicks outside the modal, it should close
> feat: Closes modal when user clicks outside

- src/style.css
> fix(style.css): made mobile responsive

- src/style.css
Closes  #65
- add background-color '#9580ff' 
- add color'#ffffff' 
- change font-size on viewport '444px' to 1.3rem 
- some more minor changes to make it responsive.
> Fixed footer responsiveness issue.

- CONTRIBUTING.md
> chore(contributing.md): add some rules

- index.html
- src/general.ts
- src/generators/gradient-background.ts
- src/main.ts
- src/style.css
- Add Background Gradient generator
- Reduce size of h2 element in generator cards
> feat: add gradient background

- src/style.css
Closes #71 
* centered all the generator cards on mobile devices
* improved the alignment of h2 text on generator cards
* centered the get result button text in modal
> fixed generator alignment, improved generator text alignment

- CONTRIBUTING.md
fixes #78 
remove extra bullet point
> Remove extra bullet point

- README.md
fixes #69 
gitpodify this project
> gitpodify this project

- index.html
- src/style.css
- Fixed generator card looking stretched
> fix(src/style.css, index.html): fixed generator card's images stretching

- src/style.css
This PR resolve the https://github.com/Dun-sin/trick-generator/issues/90 issue.
- Made changes in the Nav title element, it wasn't centred properly.
- Fixed the Nav padding.
Any changes/Feedback are welcomed.
> All Nav items are centered.

- .github/ISSUE_TEMPLATE/config.yml
Fixes #100 
- don't allow user to create blank issues
> Don't allow user to create blank issues

- package.json
- src/general.ts
- src/generators/gradient-background.ts
- src/generators/gradient-border.ts
- src/generators/gradient-text.ts
- src/generators/pic-text.ts
- src/style.css
Closes #91 
- Added a popup that code has been copied to the clipboard when a user presses the 'Get Code' button on any type
of generator
- installed a package called 'eggy.js'
- Made a function showPopup
> feat: added popup that code has been copied

- src/style.css
- add animation fill mode and direction for smoother animation
> fix(style.css): fix animation by making it smooth

- .eslintrc.json
- .prettierrc
- package-lock.json
- package.json
- src/general.ts
- src/generators/gradient-background.ts
- src/generators/gradient-border.ts
- src/generators/gradient-text.ts
- src/generators/pic-text.ts
- src/main.ts
- tsconfig.json
- add general format styling to code
> style: general formatting

- src/style.css
Closes #108 
- fixed header responsiveness issue.
- decreased left and right padding on the nav element.
- added new media query on viewport '344px'
> fix: fixed header responsiveness issue

- index.html
- src/general.ts
- src/generators/animation.ts
- src/main.ts
- src/style.css
- Supports Skew, Fade & Flip animations
- Ability to change the duration, degree or amount (based on the type of animation)
- Ability to copy the CSS key frame animation 
This addition does not break the existing architecture, and only makes small additions
> Added Animation Generator

- src/style.css
- removed the padding that was making it look unresponsive
> fix(style): fix input responsiveness

- index.html
- src/generators/animation.ts
Closes #121
- A stop animation button that stops all animations executed.
- added a stop button to the animation modal
- used new button on DOM on the animation.ts file 
- added an event listener to stop animation
> feat: added stop button to animation modal

- src/general.ts
- Fixed copy to clipboard not working correctly
The get code button was not working, i.e. not copying the first time it was clicked because of an event
listener was being added in the first click, and it made the copy to clipboard code unreachable
the first time. Removing it fixed the bug.
> fix: get-code-button malfunction

- src/style.css
Closes #128 
Changes the values of the primary and secondary variables in the main stylesheet
> Change primary and secondary colors

- index.html
- src/lib/general.ts
- src/main.ts
- src/pages/animation.ts
- src/pages/gradient-background.ts
- src/pages/gradient-border.ts
- src/pages/gradient-text.ts
- src/pages/pic-text.ts
- src/style.css
- create a new sidebar
- create a result sidebar
- new UI design
> feat: change visual

- .github/workflows/build.yml
- Update the `npm install` command to `npm ci` in `build.yaml`
> Updated npm install to npm ci in build.yaml

- index.html
- src/main.ts
- src/style.css
Closes #133 
- only show nav icons on mobile screen
- make nav closable
> fix: navbar responsiveness for mobile screens

- src/main.ts
- src/style.css
> feat: add highlight for when a generator is active

- index.html
- src/main.ts
update gradient preview when either colors or degree changes
fix #134
Closes #134 
Show and update live preview if any of the following changes:
- color1
- color2
- range
> feat: show live update on gradient preview

- README.md
Closes #144
Changed the discord link to a preferred one.
> docs: Updated discord link

- src/main.ts
- src/pages/pic-text.ts
Fixed issue #151 
changes were made in  the main.ts and pic-text.ts where i wrote the codes to fix the issue
> fixed issue #151 for image get result button

- src/main.ts
Closes #163 
- deleted unnecessary comment
> refactor: delete unnecessary comment in file

- src/style.css
I have used the calc function to implement the solution
Closes #156
1) used the calc function to increase the font based on screen size
2) gave it a padding in media queries
> fix: made the text mobile responsive.

- src/pages/gradient-text.ts
Closes #192 
Changed the position of the check.
Hacktoberfest contribution
https://user-images.githubusercontent.com/18360871/193418112-08170bb9-86be-43fa-89f2-14b8a65845ca.mp4
> fix: of playing the animation even with empy field

- index.html
- src/style.css
Styled input field for duration present in the animation section
fix #185
Closes #185
- Styled and improved the input field present in the animation section.
> fix: styled input field in animation section

- src/style.css
Closes #181 
Input field styling fix - fancier number input fields
> feat: add fancier number input fields

- src/main.ts
fix #183 
- navbar is now closing when clicking outside of it.
- used 'click' EventListener for achieving this.
- used getComputedStyle() function to get display of '.menu' element.
> feat: close navbar on clicking outside

- src/pages/animation.ts
changes were made to animator.ts file
> fix: Button become inactive after first click on "Get Result" 

- src/pages/gradient-border.ts
Fixed border radius issue in gradient border section
Closes #213
- Fixed border radius issue in gradient border section.
- Now the border radius gets set to 0 when one uncheck the checkbox, or get the results
> fix: fixed border radius issue in gradient border

- src/style.css
Closes #218 
added hover effect for get results button
> feat: added hover effect for get results button

- README.md
Closes #221
Added short descriptions of css tricks available in Code-Magic
Hey!! Suggest changes if required.
> docs: Add descriptions of tricks avaiable

- README.md
Closes #228
Fixed some typos in the Magic Options section
> docs: Fix typos

- .husky/pre-commit
- package-lock.json
- package.json
closes #142 
- adds pretty-quick and husky to format the staged files before every commit.
> feat: adds husky and pretty-quick to apply prettier on every commit

- src/lib/general.ts
- src/main.ts
- Refactored document method that contains `<Type>Value` to `Value as Type`
- Files affected
- src/main.ts
- src/lib/general.ts
None
Not Applicable
> refactor: change format of adding type

- src/main.ts
Closes #245 
- [ X] My code follows the code style of this project.
- [ X] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.
> fix: sidebar sliding out bug

- index.html
- src/pages/animation.ts
Closes #256 
- add the rotation animation option to the Animator section
> feat: Add a rotation animation in Animator

- README.md
Added a short description for the box shadow generator and fixed typos.
Closes #259
> docs: add box shadow generator description and fix typos

- index.html
- src/style.css
Closes #257 
- keep similar inputs from box shadow in one div
> feat: Keep every similar input in one div

- src/style.css
Closes #270
- Added 'flex-wrap' to 'radio-group' and 'duration-label' to prevent content overflow 
- Added width and display: flex' to 'animation-radio-label' for alignment!
> fix: content overflow in Animator

- src/style.css
> fix: Fixed responsivenes

- README.md
Added Border-Radius in the readme.
This is my first time contributing if there is any issue with the pull request please give the feedback and I will try to correct it!
> docs(update readme.md): add Border radius documentation

- index.html
Improved the input element to be spread instead of horizontal to avoid double horizontal label in box shadow generator.
> fix: Improved the input element to be spread instead of horizontal

- index.html
> fix: degree not showing up in gradient text generator

- src/style.css
Closes #296 
- Added styling to the range inputs
> fix: Added styling to the range inputs (sliders)

- index.html
**HridoyHazard PR closes #303**
fixed the issue of empty deg indicator in gradient-background
> fix: degree not showing up in gradient background generator

- src/style.css
**My PR closes #323 
- changed input color width in mobile view
- changed input color height in mobile view
-
> fix: input colors width in mobile view

- src/style.css
**My PR closes #327 **
#327 
-changed the width variable in css
> fix: width variable

- src/main.ts
Gradient Background generator will now be able to display changes in gradient if the degree is moved using mouse. Previously it displayed changes only when the mouse button is released. Refer to the issue here for more details: https://github.com/Dun-sin/Code-Magic/issues/319
**My PR closes #319 **
Added an `EventListener` to `gradientBackgroundDegree` to update the gradient as the degrees keep changing gradually.
> fix: gradient background updates dynamically

- index.html
- src/lib/general.ts
- src/style.css
** My PR closes #316 **
- Updating defaul values for text shadow 
- Added copy code to clipboard for text shadow
I have not changed anyting in style.css but it's showing some changes and also some changes in index.html which I haven't made, but it's up to date with Dun-sin/Code-Magic:main
``` bash
div {
text-shadow: rgb(6, 219, 247) 2px 2px 4px;
}
```
> fix: text shaodw copy code to clipboard and updating default values

- src/style.css
> feat: suggest new ```border style``` for pic-text

- src/style.css
My PR closes #321 
- style.css updated for class `output` to center the gradient text result in mobile view
> fix(text-align): fixes alignment for gradient text result

- index.html
`domtoimg` seems to have issues with the cross-origin policy of stylesheets that is now fixed by making it anonymous.
Fixes #320 
Made the cross-origin of the stylesheet anonymous
> fix: made cross origin anonymous so `domtoimg` can render output div

- src/pages/text-shadow.ts
By adding event listener for `click`, download buttons can now be used. Also, added relevant functions for download handling.
Fixes #345
added event listener for `click` on download buttons
> fix: added event handler to look for download button

- README.md
**My PR closes #322 **
- added a brief description about Code Magic's text-shadow feature. 
Let me know if my description is not engaging enough.
> feat: added text-shadow to readme file.

- src/style.css
**My PR closes #315 
- change the tertiary colour
- made the range input look better
> feat: add better range slider

- src/style.css
- change background colour for border radius
> fix: range in border radius

- src/style.css
- remove margin top for other browsers
> fix: range thumb being off track in some browsers

- src/main.ts
- src/style.css
- add active state for mobile 
- add condition to avoid menu category
> fix(menu): disable menu closed if a category is clicked

- index.html
- src/style.css
**My PR closes #356**
- add icons to categories
> feat(icon): add icons to categories

- src/main.ts
> feat: added navigation bar functionality

- index.html
- src/lib/general.ts
- src/main.ts
- src/pages/gradient-border.ts
- src/pages/input-range.ts
- src/style.css
- add UI for range input range generator
> feat(input-range): add UI and nessacry inputs

- src/lib/general.ts
**My PR closes #366**
- Added default case in actOnGenerator function
> feat: adding default case in actOnGenerator function

- index.html
fix #369
**My PR closes #369**
- added star the project link (GitHub button)
- removed contribute to project link
Before
After
> feat: add link to star project in menu

- README.md
**My PR closes #371 **
- added description for input type range in readme
> docs: add description for input type range

- index.html
- src/lib/general.ts
- src/pages/gradient-background.ts
- src/pages/gradient-border.ts
- src/pages/gradient-text.ts
- src/style.css
clicking on add new color adds a new color picker and clicking on remove color removes the feature
- added button for adding a new color picker
- added button for removing a color picker
> feat(color): add option for extra color

- index.html
- src/lib/getElements.ts
- src/main.ts
- src/pages/animation.ts
- src/style.css
My PR closes #373 
I added an animation preview container to the animation generator and hooked it up to a function called "displayAnimationPreview", that I created in the animation.ts file. I added two new functions to getElements.ts to select the new elements I added to the HTML. I also added a bit of CSS to style the animation preview container, but I would love to hear opinions on other design options.
Lastly, added a button in the animation generator section to toggle between displaying the animation preview container.
I closed the previous pull request for this cause of some problems caused by commiting and then removing the package.json file. I really do apologize for that, I read the Contributing guidelines before I made the pull request but I was reading it sequentially and doing …
> feat: Add animation preview

- .github/pull_request_template.md
**My PR closes #392 **
Removed additional checkbox example with similar data from Pull Request Template Markdown.
> fix: removing redundant checkbox example

- README.md
My PR closes #389 
Added logo in README
> docs: New logo added 

- src/main.ts
**My PR closes #403**
Disable file opening in browser
> fix: disable file opening in browser

- src/style.css
**My PR closes #406**
- Change the Font size of the sidebar.
- Change padding and gap for sidebar.
> fix(style.css): change font size ,padding and  gap of sidebar

- index.html
- src/lib/getElements.ts
- src/lib/packages.ts
- src/pages/animation.ts
- src/pages/border-radius.ts
- src/pages/box-shadow.ts
- src/pages/gradient-background.ts
- src/pages/gradient-border.ts
- src/pages/gradient-text.ts
- src/pages/input-range.ts
- src/pages/pic-text.ts
- src/pages/text-shadow.ts
- src/pages/transform.ts
- src/style.css
"re #409"
**My PR closes #409 **
Added Tailwind buttons to the Result Pages and  functions that show a popup when clicked
> feat: added buttons for Tailwind code options

- src/style.css
overflowing border-radius layout preview
**My PR closes #418**
> fix: border layout preview

- src/lib/packages.ts
- src/pages/border-radius.ts
Added tailwind code generator for border radius property
**My PR closes #416 **
- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
> feat: tailwind border-radius code

- src/lib/packages.ts
- src/pages/gradient-text.ts
**My PR closes #411**
Added tailwind equivalent code for the gradient text
> feat: added tailwind code for gradient text

- index.html
- src/lib/packages.ts
- src/pages/gradient-background.ts
**My PR closes #412**
- remove the option to get tailwind code
> feat: removes the option to copy tailwind code for gradient background

- index.html
- src/lib/getElements.ts
- src/lib/packages.ts
- src/pages/animation.ts
- src/pages/border-radius.ts
- src/pages/box-shadow.ts
- src/pages/gradient-background.ts
- src/pages/gradient-border.ts
- src/pages/gradient-text.ts
- src/pages/input-range.ts
- src/pages/pic-text.ts
- src/pages/text-shadow.ts
- src/pages/transform.ts
- src/style.css
**My PR closes #429**
worked on making dropdowns for css/tailwind button and png/svg  buttons
https://github.com/Dun-sin/Code-Magic/assets/68906510/62d21619-de87-4916-a6ee-30bdadb79366
> feat: Buttons dropdown

- src/lib/packages.ts
- proper and working code for tailwind gradient text generator
> fix(package.ts): proper tailwind code for gradient text

- index.html
- src/pages/box-shadow.ts
**My PR closes #431**
- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
> fix: no output in box shadow

- src/main.ts
- src/style.css
added an onclick animation to the dropdown items on the sidebar
fix #445
**This PR closes #445**
> fix(main.ts style.css): add animation to sidebar dropdown menu

- .vaunt/config.yaml
- add vaunt GitHub action for achievement
> chore: add vaunt

- README.md
> docs: change gif

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/doc_issue.yml
- .github/ISSUE_TEMPLATE/features.yml
- .github/ISSUE_TEMPLATE/other.yml
- Add hacktoberfest label to issue templates
> chore: add hacktoberfest label

- src/lib/packages/helpers.ts
- src/pages/text-shadow.ts
feat #454
**My PR closes #454** 
Added the correct and tested TailwindCSS code for text-shadow property
The code has been tested locally.
> feat(helpers.ts): added tailwind code for text-shadow property

- src/style.css
**My PR closes #469 **
added align-items: center in style.css on line 424.
> fix: add and remove color button not aligned 

- src/lib/packages/helpers.ts
- src/pages/input-range.ts
**My PR closes #464 
There was no tailwind css generator in the input range. I added.
> fix(pages): fix tailwind css code for input range

- .github/ISSUE_TEMPLATE/config.yml
**My PR closes #463**
- Added correct discord URL
- Removed incorrect discord URL
> fix: Fixes invalid discord link in config.yml file issue

- src/main.ts
**My PR closes #468**
Fixed the main.ts file, and now the drop-down open or closes even if we click in the blank space.
https://github.com/Dun-sin/Code-Magic/assets/105808363/c8b9e763-acdc-4648-85a7-612f5b219352
> fix(main.ts): fixed the drop-down issue

- index.html
My PR closes #478 
Changed the logos of the "Copy CSS code" and "Copy Tailwing" buttons from the generic code logo to their respective logos.
> feat(index.html): changed the copy css and tailwind code button logos

- index.html
- src/lib/getElements.ts
- src/lib/packages/helpers.ts
- src/main.ts
- src/pages/grid-generator.ts
- src/style.css
The number of rows and columns for the grid can be obtained from the user's input, and it can be previewed in CSS grid preview, User can get the CSS code and tailwind class for the generated CSS grid
Resetting inputs will clear the preview
I have put CSS grid generation under CSS layout generation list, because in future, we can add other layouts under CSS layout generation list
Column gap and row gap can be added to generate a CSS grid more accurately
**My PR closes #434**
Initial stage
When entering the number of rows and columns
After copying the CSS code
> feat(grid layout generators): CSS layout generation has been created

- src/style.css
provide padding between parent and child element
**My PR closes #470**
> feat(src/style.css): add padding

- index.html
- src/pages/grid-generator.ts
Fixes #487
@Dun-sin can you please review the changes made? Any feedback will be highly appreciated!!
> refactor: dropdown menu implemented to create a consistent UI

- src/main.ts
Toggle arrow icon functionality added for left side navigation bar list items in docs
**My PR closes #491 **
1. Identify the iconfiy-icon element in the already added eventListener of icon element in main.ts
2. Change the icon attribute of iconify-icon from material-symbols:arrow-drop-down-rounded to material-symbols:arrow-drop-up-rounded which will result in upwards arrow and vice versa.
- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title and description of the PR is clear and explains the approach.
https://github.com/Dun-sin/Code-Magic/assets/57678528/63c5e920-71ae-4fea-8c6e-71abff98df3c
> feat: Add Toggle arrow functionality for Left Navigation Items

- src/pages/grid-generator.ts
Fixes #502
@Dun-sin I would like to know if this is the behaviour you were expecting or do I need to make any changes? Do I need to prevent the user from copying the generated code if the input values are not within the range? Any feedback would be much appreciated!
> fix: prevents overflow for larger input values in grid generator

- index.html
- src/style.css
**My PR closes #511**
- Redesigned the border-radius css styles
- Modified code in index.html to bring out the expected changes
https://github.com/Dun-sin/Code-Magic/assets/94698235/2f680494-0e31-4d0e-ab27-d8299384c5af
> fix: Modified the input border radius section of the gradient border

- index.html
Fixes #516 
I replace old OG image url.
> fix: wrong OG Image

- index.html
**My PR closes #510 **
Added the min and max range in the input field of thumb radius and track radius attribute of Input range section.
> fix: added min and max range for input

- index.html
- src/pages/text-shadow.ts
**My PR closes #537
- Added a default value for `textarea`
- Removed the empty `color` check
- Added default value for box and text shadow colors
> fix: value for the range in Text shadow doesn't update

- src/style.css
**My PR closes #534 **
Changed color of caret and placeholder in Input generator
> fix: Changed caret and placeholder color #534

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/doc_issue.yml
- .github/ISSUE_TEMPLATE/features.yml
- .github/ISSUE_TEMPLATE/other.yml
- add label -> "🚦 status: awaiting approval"
> docs: add label for awaiting approval

- src/style.css
**My PR closes #548 **
Centered generator title to the center
> feat: Centered generator title #548

- src/style.css
**My PR closes #issue_number_here**
Closes #555 
Changed the styling of the H1 text for a smaller screen size.
- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
> feat(Responsiveness): changed the sizing of H1 tag for screen size up to 500px

- index.html
- package-lock.json
- package.json
- src/main.ts
- src/pages/scroll.ts
- src/style.css
- vite.config.js
**My PR closes #553**
- added libraries for testing
- create scroll.ts for custom scroll logic
> feat(scroll.ts): add custom scroll bar generator

- index.html
**My PR closes #559 **
-I copy Pasted as informed in the issue
-Resolved any errors that occured
> refactor: move the grid generator input into the input section

- src/eggy-js.d.ts
- src/lib/packages/helpers.ts
- src/lib/packages/utils.ts
- src/main.ts
- src/pages/animation.ts
- src/pages/border-radius.ts
- src/pages/box-shadow.ts
- src/pages/gradient-background.ts
- src/pages/gradient-border.ts
- src/pages/gradient-text.ts
- src/pages/grid-generator.ts
- src/pages/input-range.ts
- src/pages/scroll.ts
- src/pages/text-shadow.ts
- src/pages/transform.ts
**My PR closes #562 **
- added url params for generators and their values
- on load the values get set into the preview and the as value of the input elements
- when reset button is clicked, the values clear
https://github.com/user-attachments/assets/09027eb4-2ffd-42c8-a608-003b723c6866
> feat: add url params
