Dun-sin/Code-Magic

src/style.css
Closes #160 
- change the placeholder colour to a higher contrast one
=> Fix: placeholder of Gradient Text component not visible

src/lib/general.ts
Fixes #198
updated the codeToCopy template literal of case: 'gradient-border' with the properties that are in element using the method .getPropertyValue()
Current output : 
Expected output :
You can see from above screenshots that the expected output fixes the issue.
=> fix: update codeToCopy template literal variable in case 'gradient-border'

src/main.ts
This PR adds a sliding and opacity animation to the NavBar when closed/expanded in mobile view.  
For#209
Fixes #209 
Use `navBar?.animate` with keyframe options to animate a sliding effect as well as changing opacity.
Do you want me to animate the hamburger menu into the X? I can try doing that if you'd like(may or may not work)
Thanks!
https://user-images.githubusercontent.com/58442255/193570193-814cb5f3-e89c-49f2-b3ef-71d7ae64fe8b.mp4
=> feat: add animation for NavBar in mobile view

src/main.ts
Made the label of filepond file uploader responsive
Closes #175 
- Made the label of filepond file uploader responsive
- The label now shows default text on screens with width above 768px, and it gets changed to "Browse" only in smaller screens
- [x] My code follows the code style of this project. 
- [x] This PR does not contain plagiarized content.
=> fix: made the label of file uploader responsive

src/main.ts
Closes #255 
- Added an event listener that clears the generator nav styling when "Code Magic" is clicked
- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
=> fix: Remove unnecessary active background

src/lib/general.ts
Closes #252 
- removed extra single-inverted-commas from Gradient text code syntax
Before 
After
=> fix: gradient text copied code

index.html, src/lib/general.ts, src/main.ts, src/pages/box-shadow.ts, src/style.css
Fixes #278
Closes #278 
The amount of box shadow in px is displayed and the box shadow inputs are interacted with.
N/A
=> feat(box-shadow): show amount of pixels immediately in box shadow

src/pages/gradient-border.ts
Closes #288 
If any or both of the color selector in gradient border are empty, animation is triggered on that selector for picking a color instead of giving result according to default red and blue colors.
=> feat(gradient-border): trigger animation on empty color selector

index.html, src/lib/general.ts, src/pages/box-shadow.ts, src/style.css
Adds a preview box that is updated when the box-shadow sliders and color are updated.
fix #279 
Closes #279 
Box shadow preview
=> feat(box-shadow): add preview in box-shadow

src/style.css
Added  `left: 3.2rem;` in box-shadow-preview class of style.css in pages folder.
Removed the previous changes.
Also, changed the title of the pull request.
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
=> fix: preview goes under the menu icon in mobile view

src/lib/general.ts
single quotes were added around height and width property of the `box-shadow` div that resulted in incorrect syntax. Removed them to fix the issue.
Fixes #339
Removed quotes around property values.
=> fix: fixed css syntax for box shadow generator

src/lib/packages.ts, src/style.css
**My PR closes #377 **
- Fixed the blank snackbar error.
-  The bug wasn't caused by an error in the package. It was just a CSS issue. A good way to prevent this error in the future is to use class selectors instead of element selectors when styling specific elements.
- Refactored the import statement for the eggy package, so it only imports the object (`{ Eggy }`) being used in the packages.ts file rather than the entire package (`* as eggyJs`). Not related to the error though, so I hope that's not a problem 😅
=> fix: blank snackbar

index.html, src/pages/gradient-background.ts
**My PR closes #430**
- Do not show the result screen if the inputs are not entered.
- Change the `Get Result` button to grey color if the inputs are not entered.
- Add an error indicator if the `Get Result` button is clicked and the input is not provided.
The button color is turned to grey when the input is not entered:
When the user tries to click on `Get Result` button without entering the input:
https://github.com/Dun-sin/Code-Magic/assets/61418965/59e76491-c971-4c45-ac03-f96c610b1e23
=> feat: Avoid gradient background results without input. 

src/pages/box-shadow.ts, src/pages/gradient-background.ts, src/pages/gradient-border.ts, src/pages/gradient-text.ts, src/pages/text-shadow.ts
**My PR closes #441 **
I have updated 5 files in total with respect of five pages (in alphabetic order): Box Shadow, Gradient Background, Gradient Border, Gradient Text, and Text Shadow. 
Box Shadow, When no color is picked, clicking the "Get Result" button will not show the side menu button ( I have not added animation like in the Text Shadow page, strickly focusing on the bug itself).
Gradient Background, When the primary/first color is not picked, clicking the "Get Result" button will not show the side menu button.
Gradient Border, When the primary/first color is not picked, clicking the "Get Result" button will not show the side menu button.
Gradient Text, When no text is entered in the top text field, clicking the "Get Result" button will not show the side menu button.
Text Shadow, …
=> fix: open results button showing wrongly #441

src/pages/gradient-border.ts
provided error indicator for gradient-border when no input is passed and prevent getting result
**My PR closes #442 **
first of all I map the values of `gradientBorderInputs` and check lengths of the values. If the `values.length <1` I called `triggerEmptyAmination` and switched the result-button to `grey` and prevent them from getting results to result-page.
=> fix: provided error indicator for gradient-border when no input #442

index.html, src/style.css
Added a common ".generator-tool-title" class under each generator content in the index.html file. To render the style, updated the style.css file. For rendering the title style, I used fixed position style for them and adjusted the left measurement according to the available media queries. However, when the max-width of the media query is **650** then, it's getting centered. 
**My PR closes #455**
Added an indication (title) of the active generator or tool on the top left corner initially. Centered on the smaller devices.
I was unsure about how it should look for the smaller devices. So, I've centered it and used the `left: auto` in the `style.css` file.
=> feat(index.html, style.css): add Indication of the active generator/tool

src/style.css
**My PR closes #515**
- Added gap in-between 'Preview' heading and thumb fixing the overlapping issue
- Added whitespace between 'Track color' , 'Thumb Color' and the input fields
- Added whitespace between the heading and the input in thumb size selection section
=> fix: appropriate whitespace to misaligned elements.

src/style.css
**My PR closes #519 **
- Fixed the issue of stretching and misalignment of the 'include thumb radius' and 'include track radius' options in mobile view for chromium based browsers.
=> fix: made input range responsive in mobile view

src/pages/box-shadow.ts
**My PR closes #507**
- the value for the range in box shadow and text shadow which wasn't  updating fixed.
https://github.com/Dun-sin/Code-Magic/assets/74947684/6e210ec9-03cc-4ac1-9945-2a644cbb3230
=> fix: the range value issue box and text shadow

index.html
**My PR closes #558**
- move the random generator category to the end
current:
previous:
=> refactor(index.html): move the random generator category to the end
